// Generated by https://quicktype.io

// MAIN DATA
interface GroupUser {
    userId: number;
    username: string;
    buildersClubMembershipType?: string;
}


interface GroupRole {
    id: number;
    name: string;
    description?: string;
    rank: number;
    memberCount: number;
}


// GROUP INFO

export interface Group {
    id: number;
    name: string;
    description: string;
    owner: GroupUser;
    roles: GroupRole[];
    shout: {
        body: string;
        poster: GroupUser;
        created: Date;
        updated: Date;
    };
    icon: string;
    memberCount: number;
    isBuildersClubOnly: boolean;
    publicEntryAllowed: boolean;
    isLocked: boolean;
}



// LOGS_DATUM -----------------------

export interface Logs {
    previousPageCursor: null;
    nextPageCursor: string;
    data: {
        actor: {
            user: GroupUser,
            role: GroupRole
        };
        actionType: string;
        description: LogDescription;
        created: Date;
    }[];
}

interface LogDescription {
    TargetId?: number;
    TargetName?: string;
    Text?: String;
    Amount?: number;
    CurrencyTypeId?: number;
    ItemDescription?: string;
    CurrencyTypeName?: string;
    OldOwnerName?: string;
    NewOwnerName?: string;
    PostDesc?: string;
}


// GROUP WALLS
// Generated by https://quicktype.io

export interface GroupWall {
    previousPageCursor: null;
    nextPageCursor: string;
    data: GroupDatum[];
}

interface GroupDatum {
    id: number;
    poster: {
        user: GroupUser;
        role: GroupRole
    };
    body: string;
    created: string;
    updated: string;
}

// GROUP EXILE
export interface ExileUser {
    ok: boolean;
}

// GROUP ACCEPT USERS

export interface GroupJoinRequests {
    previousPageCursor: string;
    nextPageCursor: string;
    data: {
        requester: {
            userId: number;
            username: string;
        }
        created: string
    }[];
}
