import { Group, GroupRole } from "./Group.d.ts";
import { Badge } from "./Badge.d.ts";

// Generated by https://quicktype.io

export interface AuthenticatedUser {
    displayName: string;
    username: string;
    id: number
}


export interface User {
    description: string;
    created: Date;
    isBanned: boolean;
    id: number;
    name: string;
    avatarUrl: string;
    headshotUrl: string;
}

// Generated by https://quicktype.io

export interface UserAvatars {
    bodyUrl: string;
    headshotUrl: string;
}

export interface UsernameSearch {
    username: string;
    id: number;
}


// Generated by https://quicktype.io
export interface UserGroup {
    group: Group;
    role: GroupRole;
    isPrimaryGroup: boolean;
}



// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface UserBadges {
    previousPageCursor: string;
    nextPageCursor: string;
    data: Badge[]
}



// Generated by https://quicktype.io

export interface UserSearch {
    previousPageCursor: null;
    nextPageCursor: null;
    data: SearchDatum[];
}

export interface SearchDatum {
    previousUsernames: string[];
    id: number;
    name: string;
    displayName: string;
}
